name: Run tests

on: push

jobs:  
  test:
    runs-on: ubuntu-latest

    name: Run project tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js ("latest" Version)
      uses: actions/setup-node@v1
      with:
        node-version: 20.11
        
    - name: npm ci
      run: npm ci

    - name: Run tests
      run: npm run test
